#!/bin/bash

# Batch generate legal and insurance calculators

# Legal Settlement Hub calculators
./generate_calculator.sh legal alimony-spousal-support-calculator "Alimony & Spousal Support Calculator" "Calculate alimony and spousal support payments"
./generate_calculator.sh legal antitrust-hhi-index-calculator "Antitrust (HHI Index) Calculator" "Calculate Herfindahl-Hirschman Index for antitrust analysis"
./generate_calculator.sh legal asbestos-settlement-calculator "Asbestos Settlement Calculator" "Calculate asbestos-related settlement amounts"
./generate_calculator.sh legal aviation-accident-compensation-calculator "Aviation Accident Compensation Calculator" "Calculate compensation for aviation accidents"
./generate_calculator.sh legal bad-faith-insurance-claim-calculator "Bad Faith Insurance Claim Calculator" "Calculate damages for bad faith insurance claims"
./generate_calculator.sh legal birth-injury-malpractice-calculator "Birth Injury Malpractice Calculator" "Calculate malpractice damages for birth injuries"
./generate_calculator.sh legal birth-injury-settlement-calculator "Birth Injury Settlement Calculator" "Calculate settlement amounts for birth injuries"
./generate_calculator.sh legal burn-injury-settlement-calculator "Burn Injury Settlement Calculator" "Calculate settlement for burn injuries"
./generate_calculator.sh legal car-accident-pain-suffering-calculator "Car Accident Pain & Suffering Calculator" "Calculate pain and suffering damages"
./generate_calculator.sh legal car-accident-settlement-calculator "Car Accident Settlement Calculator" "Calculate total car accident settlement"
./generate_calculator.sh legal catastrophic-injury-calculator "Catastrophic Injury Calculator" "Calculate compensation for catastrophic injuries"
./generate_calculator.sh legal chapter-11-bankruptcy-plan-valuation "Chapter 11 Bankruptcy Plan Valuation" "Value Chapter 11 bankruptcy reorganization plans"
./generate_calculator.sh legal child-support-calculator "Child Support Calculator" "Calculate child support payments"
./generate_calculator.sh legal class-action-settlement-calculator "Class Action Settlement Calculator" "Calculate class action lawsuit settlements"
./generate_calculator.sh legal construction-accident-claims-calculator "Construction Accident Claims Calculator" "Calculate claims for construction accidents"
./generate_calculator.sh legal contract-breach-damages-calculator "Contract Breach Damages Calculator" "Calculate damages for contract breaches"
./generate_calculator.sh legal copyright-infringement-damages-calculator "Copyright Infringement Damages Calculator" "Calculate copyright infringement damages"
./generate_calculator.sh legal defective-drug-settlement-calculator "Defective Drug Settlement Calculator" "Calculate settlements for defective drug cases"
./generate_calculator.sh legal dental-malpractice-settlement-calculator "Dental Malpractice Settlement Calculator" "Calculate dental malpractice settlements"
./generate_calculator.sh legal dog-bite-settlement-calculator "Dog Bite Settlement Calculator" "Calculate settlements for dog bite injuries"
./generate_calculator.sh legal dui-accident-settlement-calculator "DUI Accident Settlement Calculator" "Calculate settlements for DUI-related accidents"
./generate_calculator.sh legal e-discovery-cost-calculator "E-Discovery Cost Calculator" "Calculate costs for electronic discovery"
./generate_calculator.sh legal environmental-remediation-cost-estimator "Environmental Remediation Cost Estimator" "Estimate costs for environmental cleanup"
./generate_calculator.sh legal epa-fine-penalty-calculator "EPA Fine & Penalty Calculator" "Calculate EPA fines and penalties"
./generate_calculator.sh legal fela-settlement-calculator "FELA Settlement Calculator (Railroad)" "Calculate FELA railroad injury settlements"
./generate_calculator.sh legal high-net-worth-divorce-asset-division-calculator "High-Net-Worth Divorce Asset Division Calculator" "Calculate asset division in high-net-worth divorces"
./generate_calculator.sh legal hit-and-run-settlement-calculator "Hit and Run Settlement Calculator" "Calculate settlements for hit and run accidents"
./generate_calculator.sh legal hospital-negligence-settlement-calculator "Hospital Negligence Settlement Calculator" "Calculate hospital negligence settlements"
./generate_calculator.sh legal intellectual-property-licensing-royalty-calculator "Intellectual Property Licensing Royalty Calculator" "Calculate IP licensing royalties"
./generate_calculator.sh legal irs-offer-in-compromise-calculator "IRS Offer in Compromise (OIC) Calculator" "Calculate IRS offer in compromise amounts"
./generate_calculator.sh legal jones-act-settlement-calculator "Jones Act Settlement Calculator (Maritime)" "Calculate Jones Act maritime injury settlements"
./generate_calculator.sh legal legal-malpractice-damages-calculator "Legal Malpractice Damages Calculator" "Calculate legal malpractice damages"
./generate_calculator.sh legal legal-malpractice-insurance-calculator "Legal Malpractice Insurance Calculator" "Calculate legal malpractice insurance needs"
./generate_calculator.sh legal legal-practice-valuation-calculator "Legal Practice Valuation Calculator" "Value legal practices for sale"
./generate_calculator.sh legal libel-slander-per-se-damages-estimator "Libel/Slander Per Se Damages Estimator" "Estimate damages for libel and slander"
./generate_calculator.sh legal loss-of-consortium-damages-calculator "Loss of Consortium Damages Calculator" "Calculate loss of consortium damages"
./generate_calculator.sh legal maritime-injury-compensation-calculator "Maritime Injury Compensation Calculator" "Calculate maritime injury compensation"
./generate_calculator.sh legal mass-tort-settlement-calculator "Mass Tort Settlement Calculator" "Calculate mass tort lawsuit settlements"
./generate_calculator.sh legal medical-device-liability-calculator "Medical Device Liability Calculator" "Calculate medical device liability claims"
./generate_calculator.sh legal medical-malpractice-damages-calculator "Medical Malpractice Damages Calculator" "Calculate medical malpractice damages"
./generate_calculator.sh legal medical-malpractice-insurance-calculator "Medical Malpractice Insurance Calculator" "Calculate medical malpractice insurance"
./generate_calculator.sh legal medical-malpractice-settlement-calculator "Medical Malpractice Settlement Calculator" "Calculate medical malpractice settlements"
./generate_calculator.sh legal merger-acquisition-divestiture-valuation "Merger & Acquisition (M&A) Divestiture Valuation" "Value M&A divestitures"
./generate_calculator.sh legal mesothelioma-settlement-calculator "Mesothelioma Settlement Calculator" "Calculate mesothelioma asbestos settlements"
./generate_calculator.sh legal motorcycle-accident-compensation-calculator "Motorcycle Accident Compensation Calculator" "Calculate motorcycle accident compensation"
./generate_calculator.sh legal non-compete-agreement-buyout-calculator "Non-Compete Agreement Buyout Calculator" "Calculate non-compete agreement buyouts"
./generate_calculator.sh legal nursing-home-abuse-settlement-calculator "Nursing Home Abuse Settlement Calculator" "Calculate nursing home abuse settlements"
./generate_calculator.sh legal nursing-home-negligence-calculator "Nursing Home Negligence Calculator" "Calculate nursing home negligence claims"
./generate_calculator.sh legal offshore-accident-lawyer-fee-calculator "Offshore Accident Lawyer Fee Calculator" "Calculate lawyer fees for offshore accidents"
./generate_calculator.sh legal opioid-settlement-calculator "Opioid Settlement Calculator" "Calculate opioid-related settlements"
./generate_calculator.sh legal patent-valuation-calculator "Patent Valuation Calculator" "Value patents for licensing or sale"
./generate_calculator.sh legal pedestrian-accident-settlement-calculator "Pedestrian Accident Settlement Calculator" "Calculate pedestrian accident settlements"
./generate_calculator.sh legal personal-injury-multiplier-calculator "Personal Injury Multiplier Calculator" "Calculate personal injury settlement multipliers"
./generate_calculator.sh legal pharmaceutical-liability-calculator "Pharmaceutical Liability Calculator" "Calculate pharmaceutical liability claims"
./generate_calculator.sh legal preference-payment-clawback-calculator "Preference Payment Clawback Calculator" "Calculate preference payment clawbacks in bankruptcy"
./generate_calculator.sh legal premises-liability-settlement-calculator "Premises Liability Settlement Calculator" "Calculate premises liability settlements"
./generate_calculator.sh legal prenuptial-agreement-value-calculator "Prenuptial Agreement Value Calculator" "Value prenuptial agreements"
./generate_calculator.sh legal price-fixing-overcharge-estimator "Price-Fixing Overcharge Estimator" "Estimate overcharges from price-fixing"
./generate_calculator.sh legal product-liability-insurance-calculator "Product Liability Insurance Calculator" "Calculate product liability insurance needs"
./generate_calculator.sh legal product-liability-settlement-calculator "Product Liability Settlement Calculator" "Calculate product liability settlements"
./generate_calculator.sh legal professional-liability-insurance-calculator "Professional Liability Insurance Calculator" "Calculate professional liability insurance"
./generate_calculator.sh legal property-tax-appeal-savings-calculator "Property Tax Appeal Savings Calculator" "Calculate savings from property tax appeals"
./generate_calculator.sh legal qui-tam-whistleblower-reward-calculator "Qui Tam (Whistleblower) Reward Calculator" "Calculate qui tam whistleblower rewards"
./generate_calculator.sh legal railroad-accident-settlement-calculator "Railroad Accident Settlement Calculator" "Calculate railroad accident settlements"
./generate_calculator.sh legal roundup-settlement-calculator "Roundup Settlement Calculator" "Calculate Roundup herbicide settlements"
./generate_calculator.sh legal slip-and-fall-damages-calculator "Slip and Fall Damages Calculator" "Calculate slip and fall damages"
./generate_calculator.sh legal slip-and-fall-settlement-calculator "Slip and Fall Settlement Calculator" "Calculate slip and fall settlements"
./generate_calculator.sh legal spinal-cord-injury-compensation-calculator "Spinal Cord Injury Compensation Calculator" "Calculate spinal cord injury compensation"
./generate_calculator.sh legal surgical-error-settlement-calculator "Surgical Error Settlement Calculator" "Calculate surgical error settlements"
./generate_calculator.sh legal talcum-powder-settlement-calculator "Talcum Powder Settlement Calculator" "Calculate talcum powder settlements"
./generate_calculator.sh legal trademark-valuation-calculator "Trademark Valuation Calculator" "Value trademarks for licensing or sale"
./generate_calculator.sh legal trade-secret-misappropriation-damages-calculator "Trade Secret Misappropriation Damages Calculator" "Calculate trade secret misappropriation damages"
./generate_calculator.sh legal traumatic-brain-injury-settlement-calculator "Traumatic Brain Injury Settlement Calculator" "Calculate TBI settlements"
./generate_calculator.sh legal truck-accident-settlement-calculator "Truck Accident Settlement Calculator" "Calculate truck accident settlements"
./generate_calculator.sh legal veterinary-malpractice-calculator "Veterinary Malpractice Calculator" "Calculate veterinary malpractice claims"
./generate_calculator.sh legal workers-compensation-settlement-calculator "Workers' Compensation Settlement Calculator" "Calculate workers' compensation settlements"
./generate_calculator.sh legal workers-comp-settlement-calculator "Workers' Comp Settlement Calculator" "Calculate workers' comp settlements"
./generate_calculator.sh legal wrongful-death-settlement-calculator "Wrongful Death Settlement Calculator" "Calculate wrongful death settlements"
./generate_calculator.sh legal zoning-variance-economic-impact-calculator "Zoning Variance Economic Impact Calculator" "Calculate economic impact of zoning variances"

# Insurance Hub calculators
./generate_calculator.sh legal actuarial-mortality-table-calculator "Actuarial Mortality Table Calculator" "Calculate life expectancy using actuarial tables"
./generate_calculator.sh legal auto-insurance-calculator "Auto Insurance Calculator" "Calculate auto insurance premiums"
./generate_calculator.sh legal aviation-insurance-calculator "Aviation Insurance Calculator" "Calculate aviation insurance premiums"
./generate_calculator.sh legal business-insurance-calculator "Business Insurance Calculator" "Calculate business insurance needs"
./generate_calculator.sh legal buy-sell-agreement-insurance-calculator "Buy-Sell Agreement Insurance Calculator" "Calculate buy-sell agreement insurance"
./generate_calculator.sh legal cash-value-accumulation-test-calculator "Cash Value Accumulation Test (CVAT) Calculator" "Calculate CVAT for life insurance"
./generate_calculator.sh legal catastrophe-bond-pricing-model "Catastrophe Bond Pricing Model" "Price catastrophe bonds"
./generate_calculator.sh legal ceding-commission-calculator "Ceding Commission Calculator" "Calculate reinsurance ceding commissions"
./generate_calculator.sh legal combined-ratio-calculator "Combined Ratio Calculator" "Calculate insurance combined ratios"
./generate_calculator.sh legal commercial-auto-insurance-calculator "Commercial Auto Insurance Calculator" "Calculate commercial auto insurance"
./generate_calculator.sh legal commercial-fleet-insurance-premium-estimator "Commercial Fleet Insurance Premium Estimator" "Estimate commercial fleet insurance premiums"
./generate_calculator.sh legal cyber-liability-insurance-calculator "Cyber Liability Insurance Calculator" "Calculate cyber liability insurance"
./generate_calculator.sh legal directors-officers-insurance-calculator "Directors & Officers Insurance Calculator" "Calculate D&O insurance premiums"
./generate_calculator.sh legal disability-insurance-calculator "Disability Insurance Calculator" "Calculate disability insurance needs"
./generate_calculator.sh legal disability-insurance-needs-calculator "Disability Insurance Needs Calculator" "Calculate disability insurance coverage needs"
./generate_calculator.sh legal employment-practices-liability-calculator "Employment Practices Liability Calculator" "Calculate EPL insurance"
./generate_calculator.sh legal errors-omissions-insurance-calculator "Errors & Omissions Insurance Calculator" "Calculate E&O insurance"
./generate_calculator.sh legal estate-tax-life-insurance-calculator "Estate Tax Life Insurance Calculator" "Calculate life insurance for estate tax"
./generate_calculator.sh legal expense-ratio-calculator "Expense Ratio Calculator" "Calculate insurance expense ratios"
./generate_calculator.sh legal flood-risk-zonal-pricing-calculator "Flood Risk Zonal Pricing Calculator" "Calculate flood insurance zonal pricing"
./generate_calculator.sh legal general-liability-insurance-calculator "General Liability Insurance Calculator" "Calculate general liability insurance"
./generate_calculator.sh legal guideline-premium-test-calculator "Guideline Premium Test (GPT) Calculator" "Calculate GPT for life insurance"
./generate_calculator.sh legal health-insurance-calculator "Health Insurance Calculator" "Calculate health insurance premiums"
./generate_calculator.sh legal incurred-but-not-reported-reserve-estimator "Incurred But Not Reported (IBNR) Reserve Estimator" "Estimate IBNR reserves"
./generate_calculator.sh legal key-person-insurance-calculator "Key Person Insurance Calculator" "Calculate key person life insurance"
./generate_calculator.sh legal key-person-life-insurance-calculator "Key Person Life Insurance Calculator" "Calculate key person life insurance"
./generate_calculator.sh legal kidnap-ransom-insurance-calculator "Kidnap & Ransom Insurance Calculator" "Calculate kidnap and ransom insurance"
./generate_calculator.sh legal lapse-rate-sensitivity-analysis "Lapse Rate Sensitivity Analysis" "Analyze lapse rate sensitivity"
./generate_calculator.sh legal liability-insurance-calculator "Liability Insurance Calculator" "Calculate liability insurance premiums"
./generate_calculator.sh legal life-insurance-needs-calculator "Life Insurance Needs Calculator" "Calculate life insurance coverage needs"
./generate_calculator.sh legal long-term-care-insurance-calculator "Long-Term Care Insurance Calculator" "Calculate LTC insurance premiums"
./generate_calculator.sh legal long-term-disability-elimination-period-calculator "Long-Term Disability (LTD) Elimination Period Calculator" "Calculate LTD elimination periods"
./generate_calculator.sh legal loss-ratio-calculator "Loss Ratio Calculator" "Calculate insurance loss ratios"
./generate_calculator.sh legal marine-cargo-insurance-premium-calculator "Marine Cargo Insurance Premium Calculator" "Calculate marine cargo insurance"
./generate_calculator.sh legal marine-insurance-calculator "Marine Insurance Calculator" "Calculate marine insurance premiums"
./generate_calculator.sh legal pet-insurance-calculator "Pet Insurance Calculator" "Calculate pet insurance premiums"
./generate_calculator.sh legal political-risk-insurance-calculator "Political Risk Insurance Calculator" "Calculate political risk insurance"
./generate_calculator.sh legal policy-lapse-rate-calculator "Policy Lapse Rate Calculator" "Calculate policy lapse rates"
./generate_calculator.sh legal premium-deficiency-reserve-calculator "Premium Deficiency Reserve (PDR) Calculator" "Calculate PDR reserves"
./generate_calculator.sh legal self-funded-health-plan-vs-fully-insured-calculator "Self-Funded Health Plan vs. Fully-Insured Calculator" "Compare self-funded vs fully-insured health plans"
./generate_calculator.sh legal split-dollar-life-insurance-calculator "Split Dollar Life Insurance Calculator" "Calculate split dollar life insurance"
./generate_calculator.sh legal stop-loss-insurance-premium-calculator "Stop-Loss Insurance Premium Calculator" "Calculate stop-loss insurance premiums"
./generate_calculator.sh legal surety-bond-premium-calculator "Surety Bond Premium Calculator" "Calculate surety bond premiums"
./generate_calculator.sh legal term-vs-universal-life-insurance-calculator "Term vs. Universal Life Insurance Calculator" "Compare term vs universal life insurance"
./generate_calculator.sh legal term-vs-whole-life-calculator "Term vs. Whole Life Calculator" "Compare term vs whole life insurance"
./generate_calculator.sh legal terrorism-insurance-calculator "Terrorism Insurance Calculator" "Calculate terrorism insurance premiums"
./generate_calculator.sh legal trade-credit-insurance-roi-calculator "Trade Credit Insurance ROI Calculator" "Calculate ROI for trade credit insurance"
./generate_calculator.sh legal travel-insurance-calculator "Travel Insurance Calculator" "Calculate travel insurance premiums"
./generate_calculator.sh legal umbrella-insurance-calculator "Umbrella Insurance Calculator" "Calculate umbrella insurance coverage"
./generate_calculator.sh legal umbrella-insurance-coverage-calculator "Umbrella Insurance Coverage Calculator" "Calculate umbrella insurance needs"
./generate_calculator.sh legal wildfire-risk-scoring-calculator "Wildfire Risk Scoring Calculator" "Score wildfire risk for insurance"
./generate_calculator.sh legal workers-compensation-insurance-calculator "Workers' Compensation Insurance Calculator" "Calculate workers' comp insurance"

echo "Legal and Insurance batch generation completed. Remember to register all calculators in src/calculators/index.ts"