import { NftRoyaltyRevenueCalculatorExistsButNeedsRegistrationCalculator } from './NftRoyaltyRevenueCalculatorExistsButNeedsRegistrationCalculator';

export { NftRoyaltyRevenueCalculatorExistsButNeedsRegistrationCalculator };