import { Calculator } from '../../../types/calculator';
import { calculateIndustrialWarehouseProfitability, generateIndustrialWarehouseProfitabilityAnalysis } from './formulas';
import { validateIndustrialWarehouseProfitabilityInputs } from './validation';

export const IndustrialWarehouseProfitabilityCalculator: Calculator = {
  id: 'industrial-warehouse-profitability-calculator',
  name: 'Industrial Warehouse Profitability Calculator',
  category: 'finance',
  subcategory: 'investment',
  description: 'Calculate industrial warehouse profitability, ROI, and investment returns based on construction costs, rental rates, operating expenses, and market factors.',
  inputs: [
    { id: 'totalSquareFootage', name: 'Total Square Footage', type: 'number', unit: 'sqft', required: true, description: 'Total warehouse square footage', placeholder: '50000', min: 1000, max: 1000000 },
    { id: 'warehouseType', name: 'Warehouse Type', type: 'select', required: false, description: 'Type of industrial warehouse', options: ['distribution-center', 'fulfillment-center', 'cold-storage', 'bulk-storage', 'cross-dock', 'flex-space', 'manufacturing', 'logistics-hub'] },
    { id: 'clearHeight', name: 'Clear Height', type: 'number', unit: 'ft', required: false, description: 'Clear ceiling height', placeholder: '32', min: 12, max: 100 },
    { id: 'loadingDocks', name: 'Loading Docks', type: 'number', required: false, description: 'Number of loading docks', placeholder: '10', min: 0, max: 100 },
    { id: 'parkingSpaces', name: 'Parking Spaces', type: 'number', required: false, description: 'Number of parking spaces', placeholder: '50', min: 0, max: 1000 },
    { id: 'officeSpace', name: 'Office Space', type: 'number', unit: 'sqft', required: false, description: 'Office space square footage', placeholder: '2000', min: 0, max: 50000 },
    { id: 'landArea', name: 'Land Area', type: 'number', unit: 'acres', required: false, description: 'Total land area in acres', placeholder: '10', min: 0.1, max: 1000 },
    { id: 'locationType', name: 'Location Type', type: 'select', required: false, description: 'Location classification', options: ['urban', 'suburban', 'rural', 'airport-proximity', 'port-proximity', 'highway-access', 'rail-access'] },
    { id: 'marketType', name: 'Market Type', type: 'select', required: false, description: 'Market classification', options: ['primary', 'secondary', 'tertiary', 'emerging', 'mature', 'declining'] },
    { id: 'competitionLevel', name: 'Competition Level', type: 'select', required: false, description: 'Market competition level', options: ['low', 'medium', 'high', 'very-high'] },
    { id: 'demandGrowth', name: 'Demand Growth', type: 'select', required: false, description: 'Market demand growth', options: ['declining', 'stable', 'growing', 'rapid-growth'] },
    { id: 'vacancyRate', name: 'Vacancy Rate', type: 'number', required: false, description: 'Market vacancy rate percentage', placeholder: '5', min: 0, max: 50 },
    { id: 'rentalRate', name: 'Rental Rate', type: 'number', unit: 'USD/sqft/year', required: false, description: 'Annual rental rate per square foot', placeholder: '8', min: 1, max: 50 },
    { id: 'rentalEscalation', name: 'Rental Escalation', type: 'number', required: false, description: 'Annual rental escalation percentage', placeholder: '3', min: 0, max: 20 },
    { id: 'landCost', name: 'Land Cost', type: 'number', unit: 'USD', required: false, description: 'Total land acquisition cost', placeholder: '2000000', min: 0, max: 100000000 },
    { id: 'landCostPerAcre', name: 'Land Cost per Acre', type: 'number', unit: 'USD/acre', required: false, description: 'Land cost per acre', placeholder: '200000', min: 0, max: 10000000 },
    { id: 'constructionCost', name: 'Construction Cost', type: 'number', unit: 'USD/sqft', required: false, description: 'Construction cost per square foot', placeholder: '80', min: 20, max: 300 },
    { id: 'softCosts', name: 'Soft Costs', type: 'number', unit: 'USD', required: false, description: 'Total soft costs', placeholder: '1000000', min: 0, max: 50000000 },
    { id: 'softCostPercentage', name: 'Soft Cost Percentage', type: 'number', required: false, description: 'Soft costs as percentage of construction', placeholder: '15', min: 0, max: 50 },
    { id: 'siteWork', name: 'Site Work', type: 'number', unit: 'USD', required: false, description: 'Site work and infrastructure costs', placeholder: '500000', min: 0, max: 10000000 },
    { id: 'utilityConnectionCosts', name: 'Utility Connection Costs', type: 'number', unit: 'USD', required: false, description: 'Utility connection costs', placeholder: '200000', min: 0, max: 5000000 },
    { id: 'permits', name: 'Permits', type: 'number', unit: 'USD', required: false, description: 'Permit and approval costs', placeholder: '100000', min: 0, max: 2000000 },
    { id: 'financingCosts', name: 'Financing Costs', type: 'number', unit: 'USD', required: false, description: 'Financing and closing costs', placeholder: '300000', min: 0, max: 5000000 },
    { id: 'contingency', name: 'Contingency', type: 'number', required: false, description: 'Contingency percentage', placeholder: '10', min: 0, max: 30 },
    { id: 'operatingExpenses', name: 'Operating Expenses', type: 'number', unit: 'USD/sqft/year', required: false, description: 'Annual operating expenses per square foot', placeholder: '2.5', min: 0.5, max: 10 },
    { id: 'propertyTaxes', name: 'Property Taxes', type: 'number', unit: 'USD/sqft/year', required: false, description: 'Annual property taxes per square foot', placeholder: '1.2', min: 0.1, max: 5 },
    { id: 'insurance', name: 'Insurance', type: 'number', unit: 'USD/sqft/year', required: false, description: 'Annual insurance per square foot', placeholder: '0.3', min: 0.05, max: 2 },
    { id: 'maintenance', name: 'Maintenance', type: 'number', unit: 'USD/sqft/year', required: false, description: 'Annual maintenance per square foot', placeholder: '0.8', min: 0.1, max: 3 },
    { id: 'annualUtilities', name: 'Annual Utilities', type: 'number', unit: 'USD/sqft/year', required: false, description: 'Annual utilities per square foot', placeholder: '0.2', min: 0.05, max: 1 },
    { id: 'managementFees', name: 'Management Fees', type: 'number', required: false, description: 'Management fees as percentage of gross income', placeholder: '5', min: 0, max: 15 },
    { id: 'financingRate', name: 'Financing Rate', type: 'number', required: false, description: 'Annual interest rate', placeholder: '6', min: 0, max: 20 },
    { id: 'loanTerm', name: 'Loan Term', type: 'number', required: false, description: 'Loan term in years', placeholder: '25', min: 5, max: 40 },
    { id: 'downPayment', name: 'Down Payment', type: 'number', required: false, description: 'Down payment percentage', placeholder: '25', min: 0, max: 50 },
    { id: 'taxRate', name: 'Tax Rate', type: 'number', required: false, description: 'Effective tax rate percentage', placeholder: '25', min: 0, max: 50 },
    { id: 'depreciationPeriod', name: 'Depreciation Period', type: 'number', required: false, description: 'Depreciation period in years', placeholder: '39', min: 15, max: 50 },
    { id: 'inflationRate', name: 'Inflation Rate', type: 'number', required: false, description: 'Annual inflation rate', placeholder: '3', min: 0, max: 20 },
    { id: 'exitYear', name: 'Exit Year', type: 'number', required: false, description: 'Expected exit year', placeholder: '10', min: 3, max: 30 },
    { id: 'exitCapRate', name: 'Exit Cap Rate', type: 'number', required: false, description: 'Exit capitalization rate percentage', placeholder: '6', min: 3, max: 15 },
    { id: 'tenantImprovements', name: 'Tenant Improvements', type: 'number', unit: 'USD/sqft', required: false, description: 'Tenant improvement allowance per square foot', placeholder: '5', min: 0, max: 50 },
    { id: 'leasingCommissions', name: 'Leasing Commissions', type: 'number', required: false, description: 'Leasing commissions as percentage of rent', placeholder: '4', min: 0, max: 10 },
    { id: 'brokerageFees', name: 'Brokerage Fees', type: 'number', required: false, description: 'Brokerage fees as percentage of sale price', placeholder: '3', min: 0, max: 8 },
    { id: 'environmentalCosts', name: 'Environmental Costs', type: 'number', unit: 'USD', required: false, description: 'Environmental assessment and remediation costs', placeholder: '50000', min: 0, max: 2000000 },
    { id: 'zoningCosts', name: 'Zoning Costs', type: 'number', unit: 'USD', required: false, description: 'Zoning and entitlement costs', placeholder: '100000', min: 0, max: 1000000 },
    { id: 'marketRentGrowth', name: 'Market Rent Growth', type: 'number', required: false, description: 'Annual market rent growth percentage', placeholder: '2', min: -10, max: 20 },
    { id: 'expenseGrowth', type: 'number', required: false, description: 'Annual expense growth percentage', placeholder: '2.5', min: 0, max: 15 },
    { id: 'constructionTime', name: 'Construction Time', type: 'number', required: false, description: 'Construction time in months', placeholder: '12', min: 3, max: 36 },
    { id: 'stabilizationTime', name: 'Stabilization Time', type: 'number', required: false, description: 'Time to stabilization in months', placeholder: '6', min: 0, max: 24 },
    { id: 'energyEfficiency', name: 'Energy Efficiency', type: 'select', required: false, description: 'Energy efficiency rating', options: ['basic', 'standard', 'efficient', 'green', 'leed-certified'] },
    { id: 'sustainabilityFeatures', name: 'Sustainability Features', type: 'multiselect', required: false, description: 'Sustainability features', options: ['solar-panels', 'led-lighting', 'high-efficiency-hvac', 'water-conservation', 'waste-recycling', 'green-roof', 'ev-charging', 'bike-facilities'] },
    { id: 'technologyFeatures', name: 'Technology Features', type: 'multiselect', required: false, description: 'Technology features', options: ['automated-systems', 'smart-building', 'security-systems', 'fire-suppression', 'climate-control', 'inventory-tracking', 'loading-automation', 'warehouse-management'] },
    { id: 'accessibility', name: 'Accessibility', type: 'select', required: false, description: 'Transportation accessibility', options: ['excellent', 'good', 'fair', 'poor'] },
    { id: 'infrastructure', name: 'Infrastructure', type: 'select', required: false, description: 'Infrastructure quality', options: ['excellent', 'good', 'fair', 'poor'] },
    { id: 'workforceAvailability', name: 'Workforce Availability', type: 'select', required: false, description: 'Local workforce availability', options: ['excellent', 'good', 'fair', 'poor'] },
    { id: 'regulatoryEnvironment', name: 'Regulatory Environment', type: 'select', required: false, description: 'Regulatory environment', options: ['business-friendly', 'moderate', 'restrictive', 'very-restrictive'] }
  ],
  outputs: [
    { id: 'totalInvestment', name: 'Total Investment', type: 'number', unit: 'USD', description: 'Total project investment required' },
    { id: 'constructionCostTotal', name: 'Construction Cost Total', type: 'number', unit: 'USD', description: 'Total construction cost' },
    { id: 'totalProjectCost', name: 'Total Project Cost', type: 'number', unit: 'USD', description: 'Total project cost including all components' },
    { id: 'annualRevenue', name: 'Annual Revenue', type: 'number', unit: 'USD', description: 'Annual rental revenue' },
    { id: 'annualExpenses', name: 'Annual Expenses', type: 'number', unit: 'USD', description: 'Annual operating expenses' },
    { id: 'netOperatingIncome', name: 'Net Operating Income', type: 'number', unit: 'USD', description: 'Annual net operating income' },
    { id: 'cashFlow', name: 'Cash Flow', type: 'number', unit: 'USD', description: 'Annual cash flow after debt service' },
    { id: 'monthlyPayment', name: 'Monthly Payment', type: 'number', unit: 'USD', description: 'Monthly debt service payment' },
    { id: 'annualDebtService', name: 'Annual Debt Service', type: 'number', unit: 'USD', description: 'Annual debt service payment' },
    { id: 'cashOnCashReturn', name: 'Cash-on-Cash Return', type: 'number', description: 'Cash-on-cash return percentage' },
    { id: 'capRate', name: 'Cap Rate', type: 'number', description: 'Capitalization rate percentage' },
    { id: 'IRR', name: 'IRR', type: 'number', description: 'Internal rate of return percentage' },
    { id: 'paybackPeriod', name: 'Payback Period', type: 'number', description: 'Payback period in years' },
    { id: 'breakEvenOccupancy', name: 'Break-Even Occupancy', type: 'number', description: 'Break-even occupancy rate percentage' },
    { id: 'breakEvenRent', name: 'Break-Even Rent', type: 'number', unit: 'USD/sqft/year', description: 'Break-even rental rate per square foot' },
    { id: 'profitabilityScore', name: 'Profitability Score', type: 'number', description: 'Overall profitability score (0-100)' },
    { id: 'riskScore', name: 'Risk Score', type: 'number', description: 'Risk assessment score (0-100)' },
    { id: 'recommendation', name: 'Recommendation', type: 'string', description: 'Overall investment recommendation' },
    { id: 'keyMetrics', name: 'Key Metrics', type: 'string', description: 'Key financial and operational metrics' },
    { id: 'costBreakdown', name: 'Cost Breakdown', type: 'string', description: 'Detailed cost breakdown' },
    { id: 'revenueProjections', name: 'Revenue Projections', type: 'string', description: 'Revenue projections over time' },
    { id: 'sensitivityAnalysis', name: 'Sensitivity Analysis', type: 'string', description: 'Sensitivity analysis results' },
    { id: 'marketAnalysis', name: 'Market Analysis', type: 'string', description: 'Market analysis and trends' },
    { id: 'competitiveAnalysis', name: 'Competitive Analysis', type: 'string', description: 'Competitive position analysis' },
    { id: 'industrialWarehouseProfitabilityAnalysis', name: 'Industrial Warehouse Profitability Analysis', type: 'string', description: 'Comprehensive industrial warehouse profitability analysis' }
  ],
  calculate: (inputs) => {
    return calculateIndustrialWarehouseProfitability(inputs);
  },
  generateReport: (inputs, outputs) => {
    return generateIndustrialWarehouseProfitabilityAnalysis(inputs, outputs);
  },
  formulas: [
    {
      name: 'Total Investment',
      formula: 'Total Investment = Land Cost + Construction Cost + Soft Costs + Site Work + Utilities + Permits + Financing Costs + Contingency',
      description: 'Calculates the total investment required for the project'
    },
    {
      name: 'Construction Cost Total',
      formula: 'Construction Cost Total = Total Square Footage × Construction Cost per Square Foot',
      description: 'Calculates the total construction cost'
    },
    {
      name: 'Annual Revenue',
      formula: 'Annual Revenue = Total Square Footage × Rental Rate × (1 - Vacancy Rate)',
      description: 'Calculates annual rental revenue'
    },
    {
      name: 'Annual Expenses',
      formula: 'Annual Expenses = Total Square Footage × (Operating Expenses + Property Taxes + Insurance + Maintenance + Utilities)',
      description: 'Calculates annual operating expenses'
    },
    {
      name: 'Net Operating Income',
      formula: 'Net Operating Income = Annual Revenue - Annual Expenses',
      description: 'Calculates net operating income'
    },
    {
      name: 'Cap Rate',
      formula: 'Cap Rate = Net Operating Income / Total Investment × 100',
      description: 'Calculates capitalization rate'
    },
    {
      name: 'Cash-on-Cash Return',
      formula: 'Cash-on-Cash Return = Cash Flow / (Total Investment × Down Payment Percentage) × 100',
      description: 'Calculates cash-on-cash return'
    },
    {
      name: 'Break-Even Occupancy',
      formula: 'Break-Even Occupancy = Annual Expenses / (Total Square Footage × Rental Rate) × 100',
      description: 'Calculates break-even occupancy rate'
    },
    {
      name: 'Break-Even Rent',
      formula: 'Break-Even Rent = Annual Expenses / (Total Square Footage × (1 - Vacancy Rate))',
      description: 'Calculates break-even rental rate'
    },
    {
      name: 'Monthly Payment',
      formula: 'Monthly Payment = Loan Amount × (Monthly Rate × (1 + Monthly Rate)^Loan Term) / ((1 + Monthly Rate)^Loan Term - 1)',
      description: 'Calculates monthly debt service payment'
    },
    {
      name: 'Profitability Score',
      formula: 'Profitability Score = (Cap Rate × 0.4) + (Cash-on-Cash Return × 0.3) + (IRR × 0.3)',
      description: 'Calculates overall profitability score'
    },
    {
      name: 'Risk Score',
      formula: 'Risk Score = Market Risk + Construction Risk + Financing Risk + Operational Risk',
      description: 'Calculates risk assessment score'
    }
  ],
  examples: [
    {
      name: 'Standard Distribution Center',
      inputs: {
        totalSquareFootage: 50000,
        warehouseType: 'distribution-center',
        clearHeight: 32,
        loadingDocks: 10,
        parkingSpaces: 50,
        officeSpace: 2000,
        landArea: 10,
        locationType: 'suburban',
        marketType: 'primary',
        competitionLevel: 'medium',
        demandGrowth: 'growing',
        vacancyRate: 5,
        rentalRate: 8,
        rentalEscalation: 3,
        landCost: 2000000,
        constructionCost: 80,
        softCosts: 1000000,
        siteWork: 500000,
        utilities: 200000,
        permits: 100000,
        financingCosts: 300000,
        contingency: 10,
        operatingExpenses: 2.5,
        propertyTaxes: 1.2,
        insurance: 0.3,
        maintenance: 0.8,
        utilities: 0.2,
        managementFees: 5,
        financingRate: 6,
        loanTerm: 25,
        downPayment: 25,
        taxRate: 25,
        depreciationPeriod: 39,
        inflationRate: 3,
        exitYear: 10,
        exitCapRate: 6,
        marketRentGrowth: 2,
        expenseGrowth: 2.5,
        constructionTime: 12,
        stabilizationTime: 6,
        energyEfficiency: 'efficient',
        accessibility: 'excellent',
        infrastructure: 'good',
        workforceAvailability: 'good',
        regulatoryEnvironment: 'business-friendly'
      },
      description: 'Standard distribution center in a primary market'
    },
    {
      name: 'Cold Storage Facility',
      inputs: {
        totalSquareFootage: 30000,
        warehouseType: 'cold-storage',
        clearHeight: 28,
        loadingDocks: 8,
        parkingSpaces: 30,
        officeSpace: 1500,
        landArea: 8,
        locationType: 'port-proximity',
        marketType: 'primary',
        competitionLevel: 'low',
        demandGrowth: 'rapid-growth',
        vacancyRate: 3,
        rentalRate: 12,
        rentalEscalation: 4,
        landCost: 3000000,
        constructionCost: 120,
        softCosts: 1500000,
        siteWork: 800000,
        utilities: 400000,
        permits: 150000,
        financingCosts: 500000,
        contingency: 12,
        operatingExpenses: 4.5,
        propertyTaxes: 1.5,
        insurance: 0.5,
        maintenance: 1.2,
        utilities: 1.3,
        managementFees: 6,
        financingRate: 6.5,
        loanTerm: 25,
        downPayment: 30,
        taxRate: 25,
        depreciationPeriod: 39,
        inflationRate: 3,
        exitYear: 10,
        exitCapRate: 5.5,
        marketRentGrowth: 3,
        expenseGrowth: 3,
        constructionTime: 15,
        stabilizationTime: 8,
        energyEfficiency: 'green',
        accessibility: 'excellent',
        infrastructure: 'excellent',
        workforceAvailability: 'excellent',
        regulatoryEnvironment: 'business-friendly'
      },
      description: 'Cold storage facility near port with high demand'
    },
    {
      name: 'Fulfillment Center',
      inputs: {
        totalSquareFootage: 100000,
        warehouseType: 'fulfillment-center',
        clearHeight: 36,
        loadingDocks: 20,
        parkingSpaces: 100,
        officeSpace: 5000,
        landArea: 25,
        locationType: 'highway-access',
        marketType: 'primary',
        competitionLevel: 'high',
        demandGrowth: 'growing',
        vacancyRate: 7,
        rentalRate: 9,
        rentalEscalation: 2.5,
        landCost: 5000000,
        constructionCost: 90,
        softCosts: 2500000,
        siteWork: 1200000,
        utilities: 500000,
        permits: 200000,
        financingCosts: 800000,
        contingency: 8,
        operatingExpenses: 3,
        propertyTaxes: 1.4,
        insurance: 0.4,
        maintenance: 1,
        utilities: 0.2,
        managementFees: 4,
        financingRate: 5.5,
        loanTerm: 30,
        downPayment: 20,
        taxRate: 25,
        depreciationPeriod: 39,
        inflationRate: 3,
        exitYear: 10,
        exitCapRate: 6.5,
        marketRentGrowth: 2.5,
        expenseGrowth: 2.8,
        constructionTime: 18,
        stabilizationTime: 10,
        energyEfficiency: 'leed-certified',
        accessibility: 'excellent',
        infrastructure: 'excellent',
        workforceAvailability: 'excellent',
        regulatoryEnvironment: 'business-friendly'
      },
      description: 'Large fulfillment center with automation features'
    }
  ]
};
