import { managed_security_service_provider_mssp_vs_in_house_soc_calculatorCalculator } from './managed_security_service_provider_mssp_vs_in_house_soc_calculator';

export { managed_security_service_provider_mssp_vs_in_house_soc_calculatorCalculator };
