import { Calculator } from '../../types/calculator';
import { TrustFundDistributionInputs, TrustFundDistributionOutputs } from './types';
import {
  calculateTrustFundDistribution,
  generateTrustFundDistributionAnalysis
} from './formulas';
import { validateTrustFundDistributionInputs, validateTrustFundDistributionBusinessRules } from './validation';

export const TrustFundDistributionCalculator: Calculator = {
  id: 'TrustFundDistributionCalculator',
  title: 'Trust Fund Distribution Calculator',
  category: 'finance',
  subcategory: 'Estate Planning',
  description: 'Calculate trust fund distributions, tax implications, and beneficiary income projections for various trust types including revocable, irrevocable, and special needs trusts.',
  usageInstructions: [
    'Enter trust principal and annual income details',
    'Specify beneficiary information and trust parameters',
    'Select trust type and distribution frequency',
    'Review tax implications and distribution schedules',
    'Analyze beneficiary income and trust sustainability'
  ],

  inputs: [
    {
      id: 'trustPrincipal',
      label: 'Trust Principal ($)',
      type: 'currency',
      required: true,
      min: 0,
      tooltip: 'Initial principal amount in the trust'
    },
    {
      id: 'annualIncome',
      label: 'Annual Trust Income ($)',
      type: 'currency',
      required: false,
      min: 0,
      tooltip: 'Annual income generated by trust investments'
    },
    {
      id: 'beneficiaryAge',
      label: 'Beneficiary Age',
      type: 'number',
      required: true,
      min: 0,
      max: 120,
      tooltip: 'Current age of the primary beneficiary'
    },
    {
      id: 'trustDuration',
      label: 'Trust Duration (Years)',
      type: 'number',
      required: true,
      min: 1,
      max: 100,
      tooltip: 'Number of years the trust will distribute funds'
    },
    {
      id: 'distributionFrequency',
      label: 'Distribution Frequency',
      type: 'select',
      required: true,
      options: [
        { value: 'monthly', label: 'Monthly' },
        { value: 'quarterly', label: 'Quarterly' },
        { value: 'annually', label: 'Annually' }
      ],
      tooltip: 'How often distributions are made'
    },
    {
      id: 'inflationRate',
      label: 'Inflation Rate (%)',
      type: 'percentage',
      required: false,
      min: -5,
      max: 20,
      defaultValue: 3,
      step: 0.1,
      tooltip: 'Expected annual inflation rate'
    },
    {
      id: 'taxRate',
      label: 'Tax Rate (%)',
      type: 'percentage',
      required: true,
      min: 0,
      max: 50,
      step: 0.1,
      tooltip: 'Applicable tax rate on distributions'
    },
    {
      id: 'trustType',
      label: 'Trust Type',
      type: 'select',
      required: true,
      options: [
        { value: 'revocable', label: 'Revocable Living Trust' },
        { value: 'irrevocable', label: 'Irrevocable Trust' },
        { value: 'charitable', label: 'Charitable Remainder Trust' },
        { value: 'special_needs', label: 'Special Needs Trust' }
      ],
      tooltip: 'Type of trust fund'
    },
    {
      id: 'stateOfResidence',
      label: 'State of Residence',
      type: 'text',
      required: false,
      tooltip: 'State where trust is administered'
    },
    {
      id: 'numberOfBeneficiaries',
      label: 'Number of Beneficiaries',
      type: 'number',
      required: true,
      min: 1,
      max: 20,
      tooltip: 'Total number of beneficiaries'
    },
    {
      id: 'investmentReturn',
      label: 'Investment Return (%)',
      type: 'percentage',
      required: false,
      min: -20,
      max: 30,
      defaultValue: 6,
      step: 0.1,
      tooltip: 'Expected annual return on trust investments'
    },
    {
      id: 'administrativeCosts',
      label: 'Administrative Costs (%)',
      type: 'percentage',
      required: true,
      min: 0,
      max: 10,
      step: 0.1,
      tooltip: 'Annual administrative and management costs'
    },
    {
      id: 'requiredMinimumDistribution',
      label: 'Required Minimum Distribution',
      type: 'boolean',
      required: false,
      tooltip: 'Subject to RMD rules (age 73+)'
    },
    {
      id: 'generationSkipping',
      label: 'Generation-Skipping Trust',
      type: 'boolean',
      required: false,
      tooltip: 'GST designed to skip a generation for tax purposes'
    }
  ],

  outputs: [
    {
      id: 'monthlyDistribution',
      label: 'Monthly Distribution',
      type: 'currency',
      explanation: 'Average monthly distribution amount'
    },
    {
      id: 'annualDistribution',
      label: 'Annual Distribution',
      type: 'currency',
      explanation: 'Total annual distribution amount'
    },
    {
      id: 'totalDistributions',
      label: 'Total Distributions',
      type: 'currency',
      explanation: 'Total amount distributed over trust duration'
    },
    {
      id: 'remainingPrincipal',
      label: 'Remaining Principal',
      type: 'currency',
      explanation: 'Principal remaining after distributions'
    },
    {
      id: 'taxLiability',
      label: 'Tax Liability',
      type: 'currency',
      explanation: 'Total taxes owed on distributions'
    },
    {
      id: 'netDistribution',
      label: 'Net Distribution',
      type: 'currency',
      explanation: 'Distributions after taxes and fees'
    },
    {
      id: 'trustDurationYears',
      label: 'Trust Duration (Years)',
      type: 'number',
      explanation: 'Total duration of trust distributions'
    },
    {
      id: 'inflationAdjustedValue',
      label: 'Inflation-Adjusted Value',
      type: 'currency',
      explanation: 'Value adjusted for inflation'
    },
    {
      id: 'beneficiaryIncome',
      label: 'Beneficiary Income',
      type: 'currency',
      explanation: 'Income per beneficiary per distribution period'
    },
    {
      id: 'administrativeCostPercentage',
      label: 'Administrative Cost %',
      type: 'percentage',
      explanation: 'Administrative costs as percentage of distributions'
    },
    {
      id: 'distributionSchedule',
      label: 'Distribution Schedule',
      type: 'text',
      explanation: 'Projected distribution schedule'
    },
    {
      id: 'taxEfficiency',
      label: 'Tax Efficiency (%)',
      type: 'percentage',
      explanation: 'Efficiency of distributions after taxes'
    }
  ],

  formulas: [], // Will be implemented with the calculation engine

  validationRules: [], // Will be implemented with validation rules

  examples: [
    {
      title: 'Family Trust for Minor Children',
      description: 'Irrevocable trust for three minor children with moderate principal',
      inputs: {
        trustPrincipal: 500000,
        annualIncome: 25000,
        beneficiaryAge: 8,
        trustDuration: 20,
        distributionFrequency: 'quarterly',
        inflationRate: 3,
        taxRate: 25,
        trustType: 'irrevocable',
        stateOfResidence: 'CA',
        numberOfBeneficiaries: 3,
        investmentReturn: 6,
        administrativeCosts: 1.5,
        requiredMinimumDistribution: false,
        generationSkipping: true
      },
      expectedOutputs: {
        monthlyDistribution: 2083,
        annualDistribution: 25000,
        totalDistributions: 500000,
        remainingPrincipal: 0,
        taxLiability: 125000,
        netDistribution: 375000,
        trustDurationYears: 20,
        inflationAdjustedValue: 202000,
        beneficiaryIncome: 694,
        administrativeCostPercentage: 1.5,
        distributionSchedule: ['Year 1: 4 x $6250.00', 'Year 2: 4 x $6250.00'],
        taxEfficiency: 75
      }
    },
    {
      title: 'Charitable Remainder Trust',
      description: 'CRT for high-income individual with significant assets',
      inputs: {
        trustPrincipal: 2000000,
        annualIncome: 100000,
        beneficiaryAge: 65,
        trustDuration: 15,
        distributionFrequency: 'annually',
        inflationRate: 2.5,
        taxRate: 15,
        trustType: 'charitable',
        stateOfResidence: 'NY',
        numberOfBeneficiaries: 1,
        investmentReturn: 7,
        administrativeCosts: 0.8,
        requiredMinimumDistribution: true,
        generationSkipping: false
      },
      expectedOutputs: {
        monthlyDistribution: 8333,
        annualDistribution: 100000,
        totalDistributions: 1500000,
        remainingPrincipal: 500000,
        taxLiability: 225000,
        netDistribution: 1275000,
        trustDurationYears: 15,
        inflationAdjustedValue: 950000,
        beneficiaryIncome: 100000,
        administrativeCostPercentage: 0.8,
        distributionSchedule: ['Year 1: 1 x $100000.00', 'Year 2: 1 x $100000.00'],
        taxEfficiency: 85
      }
    },
    {
      title: 'Special Needs Trust',
      description: 'SNT for adult child with disabilities',
      inputs: {
        trustPrincipal: 300000,
        annualIncome: 15000,
        beneficiaryAge: 35,
        trustDuration: 30,
        distributionFrequency: 'monthly',
        inflationRate: 3.5,
        taxRate: 20,
        trustType: 'special_needs',
        stateOfResidence: 'FL',
        numberOfBeneficiaries: 1,
        investmentReturn: 5,
        administrativeCosts: 2.2,
        requiredMinimumDistribution: false,
        generationSkipping: false
      },
      expectedOutputs: {
        monthlyDistribution: 1250,
        annualDistribution: 15000,
        totalDistributions: 450000,
        remainingPrincipal: 0,
        taxLiability: 90000,
        netDistribution: 360000,
        trustDurationYears: 30,
        inflationAdjustedValue: 150000,
        beneficiaryIncome: 1250,
        administrativeCostPercentage: 2.2,
        distributionSchedule: ['Year 1: 12 x $1250.00', 'Year 2: 12 x $1250.00'],
        taxEfficiency: 80
      }
    }
  ]
};