import { Calculator } from '@/types/calculator';
import { MortgageQualificationCalculator } from './MortgageQualificationCalculator';

export const mortgageQualificationCalculator: Calculator = {
  id: 'mortgage-qualification',
  name: 'Mortgage Qualification Calculator',
  description: 'Comprehensive mortgage qualification analysis including income, debt, credit, and property evaluation to determine loan eligibility and approval probability.',
  category: 'finance',
  tags: ['mortgage', 'qualification', 'loan', 'approval', 'credit', 'income', 'debt', 'DTI', 'LTV'],
  component: MortgageQualificationCalculator,
  inputs: {
    // Borrower Information
    borrowerIncome: {
      label: 'Borrower Annual Income',
      type: 'number',
      unit: 'USD',
      required: true,
      description: 'Primary borrower\'s annual income',
      placeholder: '75000',
      min: 0,
      max: 10000000,
    },
    coBorrowerIncome: {
      label: 'Co-borrower Annual Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Co-borrower\'s annual income (if applicable)',
      placeholder: '50000',
      min: 0,
      max: 10000000,
    },
    borrowerCreditScore: {
      label: 'Borrower Credit Score',
      type: 'number',
      required: true,
      description: 'Primary borrower\'s credit score',
      placeholder: '720',
      min: 300,
      max: 850,
    },
    coBorrowerCreditScore: {
      label: 'Co-borrower Credit Score',
      type: 'number',
      required: false,
      description: 'Co-borrower\'s credit score (if applicable)',
      placeholder: '680',
      min: 0,
      max: 850,
    },
    borrowerEmploymentType: {
      label: 'Borrower Employment Type',
      type: 'select',
      required: true,
      description: 'Primary borrower\'s employment status',
      options: [
        { value: 'employed', label: 'Employed' },
        { value: 'self_employed', label: 'Self-Employed' },
        { value: 'retired', label: 'Retired' },
        { value: 'business_owner', label: 'Business Owner' },
        { value: 'unemployed', label: 'Unemployed' },
      ],
    },
    coBorrowerEmploymentType: {
      label: 'Co-borrower Employment Type',
      type: 'select',
      required: false,
      description: 'Co-borrower\'s employment status',
      options: [
        { value: 'employed', label: 'Employed' },
        { value: 'self_employed', label: 'Self-Employed' },
        { value: 'retired', label: 'Retired' },
        { value: 'business_owner', label: 'Business Owner' },
        { value: 'unemployed', label: 'Unemployed' },
      ],
    },
    borrowerEmploymentLength: {
      label: 'Borrower Employment Length',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Years of employment for primary borrower',
      placeholder: '5',
      min: 0,
      max: 50,
    },
    coBorrowerEmploymentLength: {
      label: 'Co-borrower Employment Length',
      type: 'number',
      unit: 'years',
      required: false,
      description: 'Years of employment for co-borrower',
      placeholder: '3',
      min: 0,
      max: 50,
    },

    // Income Details
    baseSalary: {
      label: 'Base Salary',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Base annual salary',
      placeholder: '70000',
      min: 0,
      max: 10000000,
    },
    overtimeIncome: {
      label: 'Overtime Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Annual overtime income',
      placeholder: '5000',
      min: 0,
      max: 1000000,
    },
    bonusIncome: {
      label: 'Bonus Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Annual bonus income',
      placeholder: '10000',
      min: 0,
      max: 1000000,
    },
    commissionIncome: {
      label: 'Commission Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Annual commission income',
      placeholder: '0',
      min: 0,
      max: 1000000,
    },
    rentalIncome: {
      label: 'Rental Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Annual rental income',
      placeholder: '0',
      min: 0,
      max: 1000000,
    },
    investmentIncome: {
      label: 'Investment Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Annual investment income',
      placeholder: '2000',
      min: 0,
      max: 1000000,
    },
    otherIncome: {
      label: 'Other Income',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Other annual income sources',
      placeholder: '0',
      min: 0,
      max: 1000000,
    },

    // Assets and Liabilities
    borrowerAssets: {
      label: 'Borrower Assets',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total assets for primary borrower',
      placeholder: '50000',
      min: 0,
      max: 100000000,
    },
    coBorrowerAssets: {
      label: 'Co-borrower Assets',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total assets for co-borrower',
      placeholder: '30000',
      min: 0,
      max: 100000000,
    },
    borrowerLiquidity: {
      label: 'Borrower Liquidity',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Liquid assets for primary borrower',
      placeholder: '25000',
      min: 0,
      max: 10000000,
    },
    coBorrowerLiquidity: {
      label: 'Co-borrower Liquidity',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Liquid assets for co-borrower',
      placeholder: '15000',
      min: 0,
      max: 10000000,
    },
    borrowerDebts: {
      label: 'Borrower Debts',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total debts for primary borrower',
      placeholder: '15000',
      min: 0,
      max: 10000000,
    },
    coBorrowerDebts: {
      label: 'Co-borrower Debts',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total debts for co-borrower',
      placeholder: '10000',
      min: 0,
      max: 10000000,
    },

    // Property Information
    propertyValue: {
      label: 'Property Value',
      type: 'number',
      unit: 'USD',
      required: true,
      description: 'Estimated property value',
      placeholder: '300000',
      min: 0,
      max: 50000000,
    },
    propertyAddress: {
      label: 'Property Address',
      type: 'text',
      required: true,
      description: 'Property address',
      placeholder: '123 Main St, Anytown, USA',
    },
    propertyType: {
      label: 'Property Type',
      type: 'select',
      required: true,
      description: 'Type of property',
      options: [
        { value: 'single_family', label: 'Single Family' },
        { value: 'multi_family', label: 'Multi-Family' },
        { value: 'condo', label: 'Condominium' },
        { value: 'townhouse', label: 'Townhouse' },
        { value: 'commercial', label: 'Commercial' },
      ],
    },
    propertySize: {
      label: 'Property Size',
      type: 'number',
      unit: 'sq ft',
      required: false,
      description: 'Property square footage',
      placeholder: '2000',
      min: 0,
      max: 100000,
    },
    propertyAge: {
      label: 'Property Age',
      type: 'number',
      unit: 'years',
      required: false,
      description: 'Age of the property',
      placeholder: '15',
      min: 0,
      max: 200,
    },

    // Loan Information
    loanAmount: {
      label: 'Loan Amount',
      type: 'number',
      unit: 'USD',
      required: true,
      description: 'Requested loan amount',
      placeholder: '240000',
      min: 0,
      max: 10000000,
    },
    interestRate: {
      label: 'Interest Rate',
      type: 'number',
      unit: '%',
      required: true,
      description: 'Annual interest rate',
      placeholder: '4.5',
      min: 0,
      max: 25,
    },
    loanTerm: {
      label: 'Loan Term',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Loan term in years',
      placeholder: '30',
      min: 0,
      max: 50,
    },
    loanType: {
      label: 'Loan Type',
      type: 'select',
      required: true,
      description: 'Type of mortgage loan',
      options: [
        { value: 'conventional', label: 'Conventional' },
        { value: 'fha', label: 'FHA' },
        { value: 'va', label: 'VA' },
        { value: 'usda', label: 'USDA' },
        { value: 'jumbo', label: 'Jumbo' },
        { value: 'hard_money', label: 'Hard Money' },
        { value: 'private', label: 'Private' },
      ],
    },
    paymentType: {
      label: 'Payment Type',
      type: 'select',
      required: true,
      description: 'Type of payment structure',
      options: [
        { value: 'principal_interest', label: 'Principal & Interest' },
        { value: 'interest_only', label: 'Interest Only' },
        { value: 'balloon', label: 'Balloon' },
        { value: 'arm', label: 'Adjustable Rate' },
      ],
    },

    // Down Payment Information
    downPayment: {
      label: 'Down Payment',
      type: 'number',
      unit: 'USD',
      required: true,
      description: 'Down payment amount',
      placeholder: '60000',
      min: 0,
      max: 50000000,
    },
    downPaymentPercentage: {
      label: 'Down Payment Percentage',
      type: 'number',
      unit: '%',
      required: true,
      description: 'Down payment as percentage of property value',
      placeholder: '20',
      min: 0,
      max: 100,
    },
    downPaymentSource: {
      label: 'Down Payment Source',
      type: 'select',
      required: true,
      description: 'Source of down payment funds',
      options: [
        { value: 'savings', label: 'Savings' },
        { value: 'investment_sale', label: 'Investment Sale' },
        { value: 'gift', label: 'Gift' },
        { value: 'inheritance', label: 'Inheritance' },
        { value: 'other', label: 'Other' },
      ],
    },

    // Insurance and Taxes
    propertyInsurance: {
      label: 'Property Insurance',
      type: 'number',
      unit: 'USD/year',
      required: false,
      description: 'Annual property insurance cost',
      placeholder: '1200',
      min: 0,
      max: 50000,
    },
    propertyTaxes: {
      label: 'Property Taxes',
      type: 'number',
      unit: 'USD/year',
      required: false,
      description: 'Annual property taxes',
      placeholder: '3600',
      min: 0,
      max: 100000,
    },
    hoaFees: {
      label: 'HOA Fees',
      type: 'number',
      unit: 'USD/month',
      required: false,
      description: 'Monthly HOA fees',
      placeholder: '0',
      min: 0,
      max: 5000,
    },
    floodInsurance: {
      label: 'Flood Insurance',
      type: 'number',
      unit: 'USD/year',
      required: false,
      description: 'Annual flood insurance cost',
      placeholder: '0',
      min: 0,
      max: 20000,
    },
    mortgageInsurance: {
      label: 'Mortgage Insurance',
      type: 'number',
      unit: 'USD/year',
      required: false,
      description: 'Annual mortgage insurance cost',
      placeholder: '0',
      min: 0,
      max: 10000,
    },
    mortgageInsuranceRate: {
      label: 'Mortgage Insurance Rate',
      type: 'number',
      unit: '%',
      required: false,
      description: 'Annual mortgage insurance rate',
      placeholder: '0',
      min: 0,
      max: 5,
    },

    // Debt Information
    creditCardDebt: {
      label: 'Credit Card Debt',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total credit card debt',
      placeholder: '5000',
      min: 0,
      max: 100000,
    },
    autoLoanDebt: {
      label: 'Auto Loan Debt',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total auto loan debt',
      placeholder: '15000',
      min: 0,
      max: 200000,
    },
    studentLoanDebt: {
      label: 'Student Loan Debt',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total student loan debt',
      placeholder: '25000',
      min: 0,
      max: 500000,
    },
    personalLoanDebt: {
      label: 'Personal Loan Debt',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Total personal loan debt',
      placeholder: '0',
      min: 0,
      max: 100000,
    },
    otherDebt: {
      label: 'Other Debt',
      type: 'number',
      unit: 'USD',
      required: false,
      description: 'Other outstanding debt',
      placeholder: '0',
      min: 0,
      max: 100000,
    },

    // Loan Program Requirements
    maxDebtToIncomeRatio: {
      label: 'Max Debt-to-Income Ratio',
      type: 'number',
      unit: '%',
      required: true,
      description: 'Maximum allowed debt-to-income ratio',
      placeholder: '43',
      min: 0,
      max: 100,
    },
    maxHousingExpenseRatio: {
      label: 'Max Housing Expense Ratio',
      type: 'number',
      unit: '%',
      required: true,
      description: 'Maximum allowed housing expense ratio',
      placeholder: '28',
      min: 0,
      max: 100,
    },
    minCreditScore: {
      label: 'Minimum Credit Score',
      type: 'number',
      required: true,
      description: 'Minimum required credit score',
      placeholder: '620',
      min: 300,
      max: 850,
    },
    minDownPayment: {
      label: 'Minimum Down Payment',
      type: 'number',
      unit: '%',
      required: true,
      description: 'Minimum required down payment percentage',
      placeholder: '3.5',
      min: 0,
      max: 100,
    },
    maxLoanAmount: {
      label: 'Maximum Loan Amount',
      type: 'number',
      unit: 'USD',
      required: true,
      description: 'Maximum allowed loan amount',
      placeholder: '548250',
      min: 0,
      max: 10000000,
    },

    // Market Information
    marketLocation: {
      label: 'Market Location',
      type: 'text',
      required: true,
      description: 'Property market location',
      placeholder: 'Suburban',
    },
    marketCondition: {
      label: 'Market Condition',
      type: 'select',
      required: true,
      description: 'Current market condition',
      options: [
        { value: 'declining', label: 'Declining' },
        { value: 'stable', label: 'Stable' },
        { value: 'growing', label: 'Growing' },
        { value: 'hot', label: 'Hot' },
      ],
    },
    marketGrowthRate: {
      label: 'Market Growth Rate',
      type: 'number',
      unit: '%',
      required: false,
      description: 'Annual market growth rate',
      placeholder: '3',
      min: -20,
      max: 50,
    },

    // Analysis Parameters
    analysisPeriod: {
      label: 'Analysis Period',
      type: 'number',
      unit: 'years',
      required: false,
      description: 'Period for analysis calculations',
      placeholder: '30',
      min: 0,
      max: 50,
    },
    inflationRate: {
      label: 'Inflation Rate',
      type: 'number',
      unit: '%',
      required: false,
      description: 'Expected annual inflation rate',
      placeholder: '2.5',
      min: -10,
      max: 50,
    },
    propertyAppreciationRate: {
      label: 'Property Appreciation Rate',
      type: 'number',
      unit: '%',
      required: false,
      description: 'Expected annual property appreciation rate',
      placeholder: '3.5',
      min: -20,
      max: 50,
    },
    discountRate: {
      label: 'Discount Rate',
      type: 'number',
      unit: '%',
      required: false,
      description: 'Discount rate for present value calculations',
      placeholder: '5',
      min: 0,
      max: 50,
    },

    // Reporting Preferences
    currency: {
      label: 'Currency',
      type: 'select',
      required: false,
      description: 'Currency for calculations',
      options: [
        { value: 'USD', label: 'US Dollar' },
        { value: 'EUR', label: 'Euro' },
        { value: 'GBP', label: 'British Pound' },
        { value: 'CAD', label: 'Canadian Dollar' },
        { value: 'AUD', label: 'Australian Dollar' },
      ],
    },
    displayFormat: {
      label: 'Display Format',
      type: 'select',
      required: false,
      description: 'Format for displaying results',
      options: [
        { value: 'percentage', label: 'Percentage' },
        { value: 'decimal', label: 'Decimal' },
        { value: 'currency', label: 'Currency' },
      ],
    },
    includeCharts: {
      label: 'Include Charts',
      type: 'boolean',
      required: false,
      description: 'Include visual charts in results',
    },
  },
  outputs: {
    qualificationScore: {
      label: 'Qualification Score',
      type: 'number',
      unit: '%',
      description: 'Overall qualification score (0-100)',
    },
    qualificationStatus: {
      label: 'Qualification Status',
      type: 'text',
      description: 'Qualification status (Approved, Conditional, Denied)',
    },
    debtToIncomeRatio: {
      label: 'Debt-to-Income Ratio',
      type: 'number',
      unit: '%',
      description: 'Total debt-to-income ratio',
    },
    housingExpenseRatio: {
      label: 'Housing Expense Ratio',
      type: 'number',
      unit: '%',
      description: 'Housing expense-to-income ratio',
    },
    averageCreditScore: {
      label: 'Average Credit Score',
      type: 'number',
      description: 'Average credit score of borrowers',
    },
    maxAffordableLoan: {
      label: 'Maximum Affordable Loan',
      type: 'number',
      unit: 'USD',
      description: 'Maximum loan amount borrower can afford',
    },
    monthlyPayment: {
      label: 'Monthly Payment',
      type: 'number',
      unit: 'USD',
      description: 'Estimated monthly mortgage payment',
    },
    probabilityOfApproval: {
      label: 'Probability of Approval',
      type: 'number',
      unit: '%',
      description: 'Probability of loan approval',
    },
    totalIncome: {
      label: 'Total Income',
      type: 'number',
      unit: 'USD',
      description: 'Combined annual income of all borrowers',
    },
    qualifyingIncome: {
      label: 'Qualifying Income',
      type: 'number',
      unit: 'USD',
      description: 'Income used for qualification calculations',
    },
    incomeStabilityScore: {
      label: 'Income Stability Score',
      type: 'number',
      unit: '%',
      description: 'Score indicating income stability',
    },
    totalDebt: {
      label: 'Total Debt',
      type: 'number',
      unit: 'USD',
      description: 'Total outstanding debt',
    },
    monthlyDebtPayments: {
      label: 'Monthly Debt Payments',
      type: 'number',
      unit: 'USD',
      description: 'Total monthly debt payments',
    },
    creditScoreRating: {
      label: 'Credit Score Rating',
      type: 'text',
      description: 'Credit score rating (Excellent, Good, Fair, Poor)',
    },
    creditRiskScore: {
      label: 'Credit Risk Score',
      type: 'number',
      unit: '%',
      description: 'Credit risk assessment score',
    },
    loanToValueRatio: {
      label: 'Loan-to-Value Ratio',
      type: 'number',
      unit: '%',
      description: 'Loan amount as percentage of property value',
    },
    propertyValueRating: {
      label: 'Property Value Rating',
      type: 'text',
      description: 'Property value assessment rating',
    },
    propertyRiskScore: {
      label: 'Property Risk Score',
      type: 'number',
      unit: '%',
      description: 'Property risk assessment score',
    },
    analysis: {
      label: 'Analysis',
      type: 'object',
      description: 'Comprehensive qualification analysis',
    },
  },
  features: [
    'Comprehensive income analysis including multiple income sources',
    'Detailed debt-to-income ratio calculations',
    'Credit score evaluation and risk assessment',
    'Property value and market analysis',
    'Multiple loan type support (Conventional, FHA, VA, USDA, Jumbo)',
    'Down payment analysis and requirements',
    'Insurance and tax considerations',
    'Employment stability assessment',
    'Asset and liquidity evaluation',
    'Market condition impact analysis',
    'Qualification score and approval probability',
    'Detailed recommendations and improvements',
    'Multiple currency support',
    'Visual charts and analysis',
  ],
  examples: [
    {
      name: 'First-time Homebuyer',
      description: 'Young couple with good credit but limited down payment',
      inputs: {
        borrowerIncome: 65000,
        coBorrowerIncome: 55000,
        borrowerCreditScore: 720,
        coBorrowerCreditScore: 690,
        propertyValue: 250000,
        loanAmount: 237500,
        downPayment: 12500,
        downPaymentPercentage: 5,
        loanType: 'fha',
      },
    },
    {
      name: 'Jumbo Loan Applicant',
      description: 'High-income borrower seeking luxury property',
      inputs: {
        borrowerIncome: 200000,
        borrowerCreditScore: 780,
        propertyValue: 800000,
        loanAmount: 640000,
        downPayment: 160000,
        downPaymentPercentage: 20,
        loanType: 'jumbo',
      },
    },
    {
      name: 'VA Loan Veteran',
      description: 'Military veteran with VA loan benefits',
      inputs: {
        borrowerIncome: 85000,
        borrowerCreditScore: 700,
        propertyValue: 350000,
        loanAmount: 350000,
        downPayment: 0,
        downPaymentPercentage: 0,
        loanType: 'va',
      },
    },
  ],
  relatedCalculators: [
    'mortgage-payment',
    'mortgage-points',
    'mortgage-life',
    'mortgage-payoff',
    'debt-to-income',
    'loan-to-value',
    'credit-score',
    'income-calculator',
  ],
};