export interface MortgageQualificationInputs {
  borrowerIncome: number;
  coBorrowerIncome?: number;
  borrowerCreditScore: number;
  coBorrowerCreditScore?: number;
  borrowerEmploymentType: 'employed' | 'self_employed' | 'retired' | 'business_owner' | 'unemployed';
  coBorrowerEmploymentType?: 'employed' | 'self_employed' | 'retired' | 'business_owner' | 'unemployed';
  borrowerEmploymentLength: number;
  coBorrowerEmploymentLength?: number;
  baseSalary: number;
  overtimeIncome?: number;
  bonusIncome?: number;
  commissionIncome?: number;
  rentalIncome?: number;
  investmentIncome?: number;
  otherIncome?: number;
  borrowerAssets: number;
  coBorrowerAssets?: number;
  borrowerLiquidity: number;
  coBorrowerLiquidity?: number;
  borrowerDebts: number;
  coBorrowerDebts?: number;
  propertyValue: number;
  propertyAddress?: string;
  propertyType: 'single_family' | 'multi_family' | 'condo' | 'townhouse' | 'commercial';
  propertySize?: number;
  propertyAge?: number;
  loanAmount: number;
  interestRate: number;
  loanTerm: number;
  loanType: 'conventional' | 'fha' | 'va' | 'usda' | 'jumbo' | 'hard_money' | 'private';
  paymentType: 'principal_interest' | 'interest_only' | 'balloon' | 'arm';
  downPayment: number;
  downPaymentPercentage: number;
  downPaymentSource: 'savings' | 'investment_sale' | 'gift' | 'inheritance' | 'other';
  propertyInsurance: number;
  propertyTaxes: number;
  hoaFees?: number;
  floodInsurance?: number;
  mortgageInsurance?: number;
  mortgageInsuranceRate?: number;
  creditCardDebt?: number;
  autoLoanDebt?: number;
  studentLoanDebt?: number;
  personalLoanDebt?: number;
  otherDebt?: number;
  maxDebtToIncomeRatio?: number;
  maxHousingExpenseRatio?: number;
  minCreditScore?: number;
  minDownPayment?: number;
  maxLoanAmount?: number;
  marketLocation?: string;
  marketCondition?: 'declining' | 'stable' | 'growing' | 'hot';
  marketGrowthRate?: number;
  analysisPeriod?: number;
  inflationRate?: number;
  propertyAppreciationRate?: number;
  discountRate?: number;
  currency?: string;
  displayFormat?: 'percentage' | 'decimal' | 'currency';
  includeCharts?: boolean;
}

export interface MortgageQualificationMetrics {
  totalIncome: number;
  qualifyingIncome: number;
  incomeStability: number;
  incomeGrowth: number;
  totalDebt: number;
  monthlyDebtPayments: number;
  debtToIncomeRatio: number;
  housingExpenseRatio: number;
  totalAssets: number;
  totalLiquidity: number;
  assetToDebtRatio: number;
  reserveRequirements: number;
  averageCreditScore: number;
  creditScoreRating: string;
  creditRisk: number;
  creditUtilization: number;
  monthlyPayment: number;
  totalMonthlyPayment: number;
  paymentToIncomeRatio: number;
  loanToValueRatio: number;
  qualificationScore: number;
  qualificationStatus: string;
  qualificationFactors: any;
  riskScore: number;
  probabilityOfApproval: number;
  probabilityOfDefault: number;
  riskFactors: any;
  maxAffordablePayment: number;
  maxAffordableLoan: number;
  maxAffordableProperty: number;
  affordabilityMargin: number;
  sensitivityMatrix: any;
  scenarios: any;
  comparisonAnalysis: any;
  timelineAnalysis: any;
}

export interface MortgageQualificationOutputs {
  qualificationScore: number;
  qualificationStatus: string;
  debtToIncomeRatio: number;
  housingExpenseRatio: number;
  averageCreditScore: number;
  maxAffordableLoan: number;
  monthlyPayment: number;
  probabilityOfApproval: number;
  totalIncome: number;
  qualifyingIncome: number;
  incomeStability: number;
  incomeGrowth: number;
  totalDebt: number;
  monthlyDebtPayments: number;
  totalAssets: number;
  totalLiquidity: number;
  assetToDebtRatio: number;
  reserveRequirements: number;
  creditScoreRating: string;
  creditRisk: number;
  creditUtilization: number;
  totalMonthlyPayment: number;
  paymentToIncomeRatio: number;
  loanToValueRatio: number;
  qualificationFactors: any;
  riskScore: number;
  probabilityOfDefault: number;
  riskFactors: any;
  maxAffordablePayment: number;
  maxAffordableProperty: number;
  affordabilityMargin: number;
  sensitivityMatrix: any;
  scenarios: any;
  comparisonAnalysis: any;
  timelineAnalysis: any;
  analysis: string;
}
