import { RealEstateInvestmentCalculatorExistsButNeedsRegistrationCalculator } from './RealEstateInvestmentCalculatorExistsButNeedsRegistrationCalculator';

export { RealEstateInvestmentCalculatorExistsButNeedsRegistrationCalculator };