import { RealEstateInvestmentCalculatorExistsButNeedsRegistrationCalculatorCalculator } from './RealEstateInvestmentCalculatorExistsButNeedsRegistrationCalculatorCalculator';

export { RealEstateInvestmentCalculatorExistsButNeedsRegistrationCalculatorCalculator };