import { Calculator } from '@/types/calculator';
import { MortgagePaymentCalculator } from './MortgagePaymentCalculator';

export const mortgagePaymentCalculator: Calculator = {
  id: 'mortgage-payment',
  name: 'Mortgage Payment Calculator',
  description: 'Calculate monthly mortgage payments, amortization schedules, and comprehensive payment analysis for various loan types including fixed-rate, ARM, interest-only, and balloon mortgages.',
  category: 'finance',
  tags: ['mortgage', 'payment', 'loan', 'real estate', 'amortization', 'ARM', 'interest-only', 'balloon'],
  component: MortgagePaymentCalculator,
  inputs: [
    {
      id: 'loanAmount',
      name: 'Loan Amount',
      type: 'number',
      required: true,
      description: 'The principal loan amount',
      placeholder: '300000',
      min: 1000,
      max: 10000000,
      step: 1000,
    },
    {
      id: 'interestRate',
      name: 'Interest Rate (%)',
      type: 'number',
      required: true,
      description: 'Annual interest rate',
      placeholder: '4.5',
      min: 0.01,
      max: 25,
      step: 0.01,
    },
    {
      id: 'loanTerm',
      name: 'Loan Term (Years)',
      type: 'select',
      required: true,
      description: 'Length of the loan in years',
      options: [
        { value: 10, label: '10 Years' },
        { value: 15, label: '15 Years' },
        { value: 20, label: '20 Years' },
        { value: 30, label: '30 Years' },
      ],
      defaultValue: 30,
    },
    {
      id: 'loanType',
      name: 'Loan Type',
      type: 'select',
      required: true,
      description: 'Type of mortgage loan',
      options: [
        { value: 'conventional', label: 'Conventional' },
        { value: 'fha', label: 'FHA' },
        { value: 'va', label: 'VA' },
        { value: 'usda', label: 'USDA' },
        { value: 'jumbo', label: 'Jumbo' },
      ],
      defaultValue: 'conventional',
    },
    {
      id: 'paymentType',
      name: 'Payment Type',
      type: 'select',
      required: true,
      description: 'Type of payment structure',
      options: [
        { value: 'principal_interest', label: 'Principal & Interest' },
        { value: 'interest_only', label: 'Interest Only' },
        { value: 'balloon', label: 'Balloon' },
        { value: 'arm', label: 'Adjustable Rate' },
      ],
      defaultValue: 'principal_interest',
    },
    {
      id: 'propertyValue',
      name: 'Property Value',
      type: 'number',
      required: true,
      description: 'Estimated property value',
      placeholder: '375000',
      min: 1000,
      max: 50000000,
      step: 1000,
    },
    {
      id: 'downPayment',
      name: 'Down Payment',
      type: 'number',
      required: true,
      description: 'Down payment amount',
      placeholder: '75000',
      min: 0,
      max: 50000000,
      step: 1000,
    },
    {
      id: 'propertyInsurance',
      name: 'Property Insurance (Annual)',
      type: 'number',
      required: false,
      description: 'Annual property insurance cost',
      placeholder: '1200',
      min: 0,
      max: 50000,
      step: 100,
      defaultValue: 1200,
    },
    {
      id: 'propertyTaxes',
      name: 'Property Taxes (Annual)',
      type: 'number',
      required: false,
      description: 'Annual property taxes',
      placeholder: '3750',
      min: 0,
      max: 100000,
      step: 100,
      defaultValue: 3750,
    },
    {
      id: 'hoaFees',
      name: 'HOA Fees (Monthly)',
      type: 'number',
      required: false,
      description: 'Monthly HOA fees',
      placeholder: '0',
      min: 0,
      max: 5000,
      step: 10,
      defaultValue: 0,
    },
    {
      id: 'borrowerIncome',
      name: 'Annual Income',
      type: 'number',
      required: false,
      description: 'Borrower annual income',
      placeholder: '80000',
      min: 1000,
      max: 10000000,
      step: 1000,
      defaultValue: 80000,
    },
    {
      id: 'borrowerCreditScore',
      name: 'Credit Score',
      type: 'number',
      required: false,
      description: 'Borrower credit score',
      placeholder: '750',
      min: 300,
      max: 850,
      step: 1,
      defaultValue: 750,
    },
    {
      id: 'paymentFrequency',
      name: 'Payment Frequency',
      type: 'select',
      required: false,
      description: 'How often payments are made',
      options: [
        { value: 'monthly', label: 'Monthly' },
        { value: 'biweekly', label: 'Bi-weekly' },
        { value: 'weekly', label: 'Weekly' },
      ],
      defaultValue: 'monthly',
    },
    {
      id: 'firstPaymentDate',
      name: 'First Payment Date',
      type: 'date',
      required: false,
      description: 'Date of first payment',
      defaultValue: new Date().toISOString().split('T')[0],
    },
  ],
  outputs: [
    {
      id: 'monthlyPayment',
      name: 'Monthly Payment',
      type: 'currency',
      description: 'Monthly principal and interest payment',
    },
    {
      id: 'totalPayment',
      name: 'Total Monthly Payment',
      type: 'currency',
      description: 'Total monthly payment including taxes and insurance',
    },
    {
      id: 'totalInterestPaid',
      name: 'Total Interest Paid',
      type: 'currency',
      description: 'Total interest paid over the life of the loan',
    },
    {
      id: 'breakEvenMonths',
      name: 'Break-Even Months',
      type: 'number',
      description: 'Number of months to break even on investment',
    },
    {
      id: 'riskScore',
      name: 'Risk Score',
      type: 'number',
      description: 'Overall risk assessment (0-100)',
    },
    {
      id: 'equityPosition',
      name: 'Current Equity',
      type: 'currency',
      description: 'Current equity position',
    },
    {
      id: 'loanToValueRatio',
      name: 'Loan-to-Value Ratio',
      type: 'percentage',
      description: 'Current loan-to-value ratio',
    },
    {
      id: 'monthlyCashFlow',
      name: 'Monthly Cash Flow',
      type: 'currency',
      description: 'Monthly cash flow after housing expenses',
    },
  ],
  features: [
    'Comprehensive mortgage payment calculations',
    'Support for multiple payment types (Fixed, ARM, Interest-Only, Balloon)',
    'Detailed amortization schedules',
    'ARM rate adjustment schedules',
    'Break-even analysis',
    'Equity and LTV calculations',
    'Cash flow analysis',
    'Risk assessment and scoring',
    'Sensitivity analysis',
    'Scenario modeling',
    'Comparison analysis',
    'Professional recommendations',
  ],
  examples: [
    {
      name: '30-Year Fixed Conventional',
      inputs: {
        loanAmount: 300000,
        interestRate: 4.5,
        loanTerm: 30,
        loanType: 'conventional',
        paymentType: 'principal_interest',
        propertyValue: 375000,
        downPayment: 75000,
        propertyInsurance: 1200,
        propertyTaxes: 3750,
        hoaFees: 0,
        borrowerIncome: 80000,
        borrowerCreditScore: 750,
        paymentFrequency: 'monthly',
        firstPaymentDate: '2024-01-01',
      },
    },
    {
      name: '5/1 ARM',
      inputs: {
        loanAmount: 400000,
        interestRate: 3.75,
        loanTerm: 30,
        loanType: 'conventional',
        paymentType: 'arm',
        propertyValue: 500000,
        downPayment: 100000,
        propertyInsurance: 1500,
        propertyTaxes: 5000,
        hoaFees: 200,
        borrowerIncome: 100000,
        borrowerCreditScore: 780,
        paymentFrequency: 'monthly',
        firstPaymentDate: '2024-01-01',
        armType: '5_1',
        initialFixedPeriod: 5,
        adjustmentPeriod: 1,
        margin: 2.5,
        indexRate: 3.0,
        lifetimeCap: 5.0,
        periodicCap: 2.0,
        floorRate: 2.0,
      },
    },
    {
      name: 'Interest-Only Investment Property',
      inputs: {
        loanAmount: 250000,
        interestRate: 5.25,
        loanTerm: 30,
        loanType: 'conventional',
        paymentType: 'interest_only',
        propertyValue: 350000,
        downPayment: 100000,
        propertyInsurance: 1000,
        propertyTaxes: 3000,
        hoaFees: 150,
        borrowerIncome: 120000,
        borrowerCreditScore: 720,
        paymentFrequency: 'monthly',
        firstPaymentDate: '2024-01-01',
      },
    },
  ],
  relatedCalculators: [
    'mortgage-refinance',
    'mortgage-points',
    'mortgage-qualification',
    'mortgage-rate-lock',
    'mortgage-vs-rent',
    'home-affordability',
    'loan-to-value-ratio',
    'debt-to-income-ratio',
  ],
};