import { Calculator } from '@/types/calculator';
import { MortgageRefinanceCalculator } from './MortgageRefinanceCalculator';

export const mortgageRefinanceCalculator: Calculator = {
  id: 'mortgage-refinance',
  name: 'Mortgage Refinance Calculator',
  description: 'Analyze the costs, benefits, and break-even analysis of refinancing your mortgage. Compare current and new loan terms, calculate savings, and determine if refinancing makes financial sense.',
  category: 'finance',
  tags: ['mortgage', 'refinance', 'loan', 'break-even', 'savings', 'interest', 'payment', 'costs'],
  component: MortgageRefinanceCalculator,
  inputs: {
    // Current Loan Info
    currentLoanAmount: {
      label: 'Current Loan Amount',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Original amount of the current mortgage loan',
      placeholder: '300000',
      min: 1000,
      max: 10000000,
    },
    currentInterestRate: {
      label: 'Current Interest Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Current annual interest rate on the mortgage',
      placeholder: '5.5',
      min: 0.1,
      max: 25,
    },
    currentLoanTerm: {
      label: 'Current Loan Term',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Original term of the current mortgage in years',
      placeholder: '30',
      min: 1,
      max: 50,
    },
    currentLoanType: {
      label: 'Current Loan Type',
      type: 'select',
      required: true,
      description: 'Type of the current mortgage loan',
      options: [
        { value: 'conventional', label: 'Conventional' },
        { value: 'fha', label: 'FHA' },
        { value: 'va', label: 'VA' },
        { value: 'usda', label: 'USDA' },
        { value: 'jumbo', label: 'Jumbo' },
        { value: 'hard_money', label: 'Hard Money' },
        { value: 'private', label: 'Private' },
      ],
    },
    currentPaymentType: {
      label: 'Current Payment Type',
      type: 'select',
      required: true,
      description: 'Type of payment structure for current loan',
      options: [
        { value: 'principal_interest', label: 'Principal & Interest' },
        { value: 'interest_only', label: 'Interest Only' },
        { value: 'balloon', label: 'Balloon' },
        { value: 'arm', label: 'Adjustable Rate' },
      ],
    },
    currentMonthlyPayment: {
      label: 'Current Monthly Payment',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Current monthly mortgage payment amount',
      placeholder: '1703.37',
      min: 1,
      max: 50000,
    },
    currentRemainingTerm: {
      label: 'Current Remaining Term',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Remaining years on the current mortgage',
      placeholder: '25',
      min: 1,
      max: 50,
    },
    currentPrincipalBalance: {
      label: 'Current Principal Balance',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Current outstanding principal balance',
      placeholder: '280000',
      min: 1,
      max: 10000000,
    },

    // New Loan Info
    newLoanAmount: {
      label: 'New Loan Amount',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Amount of the new refinanced loan',
      placeholder: '280000',
      min: 1000,
      max: 10000000,
    },
    newInterestRate: {
      label: 'New Interest Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'New annual interest rate for refinanced loan',
      placeholder: '4.0',
      min: 0.1,
      max: 25,
    },
    newLoanTerm: {
      label: 'New Loan Term',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Term of the new refinanced loan in years',
      placeholder: '30',
      min: 1,
      max: 50,
    },
    newLoanType: {
      label: 'New Loan Type',
      type: 'select',
      required: true,
      description: 'Type of the new refinanced loan',
      options: [
        { value: 'conventional', label: 'Conventional' },
        { value: 'fha', label: 'FHA' },
        { value: 'va', label: 'VA' },
        { value: 'usda', label: 'USDA' },
        { value: 'jumbo', label: 'Jumbo' },
        { value: 'hard_money', label: 'Hard Money' },
        { value: 'private', label: 'Private' },
      ],
    },
    newPaymentType: {
      label: 'New Payment Type',
      type: 'select',
      required: true,
      description: 'Type of payment structure for new loan',
      options: [
        { value: 'principal_interest', label: 'Principal & Interest' },
        { value: 'interest_only', label: 'Interest Only' },
        { value: 'balloon', label: 'Balloon' },
        { value: 'arm', label: 'Adjustable Rate' },
      ],
    },

    // Refinance Type
    refinanceType: {
      label: 'Refinance Type',
      type: 'select',
      required: true,
      description: 'Type of refinance transaction',
      options: [
        { value: 'rate_term', label: 'Rate & Term' },
        { value: 'cash_out', label: 'Cash Out' },
        { value: 'cash_in', label: 'Cash In' },
        { value: 'streamline', label: 'Streamline' },
        { value: 'fha_to_conventional', label: 'FHA to Conventional' },
      ],
    },

    // Property Info
    propertyValue: {
      label: 'Property Value',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Current estimated market value of the property',
      placeholder: '350000',
      min: 1000,
      max: 50000000,
    },
    propertyAddress: {
      label: 'Property Address',
      type: 'text',
      required: true,
      description: 'Address of the property being refinanced',
      placeholder: '123 Main St, Anytown, USA',
    },
    propertyType: {
      label: 'Property Type',
      type: 'select',
      required: true,
      description: 'Type of property being refinanced',
      options: [
        { value: 'single_family', label: 'Single Family' },
        { value: 'multi_family', label: 'Multi Family' },
        { value: 'condo', label: 'Condominium' },
        { value: 'townhouse', label: 'Townhouse' },
        { value: 'commercial', label: 'Commercial' },
      ],
    },
    propertySize: {
      label: 'Property Size',
      type: 'number',
      unit: 'sqft',
      required: false,
      description: 'Size of the property in square feet',
      placeholder: '2000',
      min: 0,
      max: 100000,
    },
    propertyAge: {
      label: 'Property Age',
      type: 'number',
      unit: 'years',
      required: false,
      description: 'Age of the property in years',
      placeholder: '15',
      min: 0,
      max: 200,
    },

    // Refinance Costs
    closingCosts: {
      label: 'Total Closing Costs',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Total closing costs for the refinance',
      placeholder: '5000',
      min: 0,
      max: 50000,
    },
    originationFee: {
      label: 'Origination Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Loan origination fee',
      placeholder: '1000',
      min: 0,
      max: 20000,
    },
    appraisalFee: {
      label: 'Appraisal Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Property appraisal fee',
      placeholder: '500',
      min: 0,
      max: 5000,
    },
    titleInsuranceFee: {
      label: 'Title Insurance Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Title insurance fee',
      placeholder: '800',
      min: 0,
      max: 10000,
    },
    recordingFee: {
      label: 'Recording Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Recording fee for mortgage documents',
      placeholder: '200',
      min: 0,
      max: 2000,
    },
    attorneyFee: {
      label: 'Attorney Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Attorney fees for closing',
      placeholder: '300',
      min: 0,
      max: 5000,
    },
    creditReportFee: {
      label: 'Credit Report Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Credit report fee',
      placeholder: '50',
      min: 0,
      max: 1000,
    },
    floodCertificationFee: {
      label: 'Flood Certification Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Flood certification fee',
      placeholder: '20',
      min: 0,
      max: 500,
    },
    taxServiceFee: {
      label: 'Tax Service Fee',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Tax service fee',
      placeholder: '100',
      min: 0,
      max: 2000,
    },
    otherFees: {
      label: 'Other Fees',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Other miscellaneous fees',
      placeholder: '1030',
      min: 0,
      max: 10000,
    },

    // Borrower Info
    borrowerIncome: {
      label: 'Borrower Income',
      type: 'number',
      unit: 'currency',
      required: true,
      description: 'Annual income of the primary borrower',
      placeholder: '80000',
      min: 1000,
      max: 10000000,
    },
    borrowerCreditScore: {
      label: 'Borrower Credit Score',
      type: 'number',
      required: true,
      description: 'Credit score of the primary borrower',
      placeholder: '750',
      min: 300,
      max: 850,
    },
    borrowerDebtToIncomeRatio: {
      label: 'Debt-to-Income Ratio',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Borrower\'s debt-to-income ratio',
      placeholder: '35',
      min: 0,
      max: 100,
    },
    borrowerEmploymentType: {
      label: 'Employment Type',
      type: 'select',
      required: true,
      description: 'Type of employment for the borrower',
      options: [
        { value: 'employed', label: 'Employed' },
        { value: 'self_employed', label: 'Self Employed' },
        { value: 'retired', label: 'Retired' },
        { value: 'business_owner', label: 'Business Owner' },
      ],
    },
    borrowerTaxRate: {
      label: 'Tax Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Borrower\'s marginal tax rate',
      placeholder: '25',
      min: 0,
      max: 50,
    },

    // Market Info
    marketLocation: {
      label: 'Market Location',
      type: 'text',
      required: true,
      description: 'Location or market area of the property',
      placeholder: 'Suburban',
    },
    marketCondition: {
      label: 'Market Condition',
      type: 'select',
      required: true,
      description: 'Current condition of the local real estate market',
      options: [
        { value: 'declining', label: 'Declining' },
        { value: 'stable', label: 'Stable' },
        { value: 'growing', label: 'Growing' },
        { value: 'hot', label: 'Hot' },
      ],
    },
    marketGrowthRate: {
      label: 'Market Growth Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Annual growth rate of the local market',
      placeholder: '3.0',
      min: -20,
      max: 50,
    },

    // Analysis Parameters
    analysisPeriod: {
      label: 'Analysis Period',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Period for financial analysis calculations',
      placeholder: '30',
      min: 1,
      max: 50,
    },
    inflationRate: {
      label: 'Inflation Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Expected annual inflation rate',
      placeholder: '2.5',
      min: -10,
      max: 50,
    },
    propertyAppreciationRate: {
      label: 'Property Appreciation Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Expected annual property appreciation rate',
      placeholder: '3.0',
      min: -20,
      max: 50,
    },
    discountRate: {
      label: 'Discount Rate',
      type: 'number',
      unit: 'percentage',
      required: true,
      description: 'Discount rate for present value calculations',
      placeholder: '5.0',
      min: 0,
      max: 50,
    },
    taxDeductionPeriod: {
      label: 'Tax Deduction Period',
      type: 'number',
      unit: 'years',
      required: true,
      description: 'Period for tax deduction calculations',
      placeholder: '30',
      min: 1,
      max: 50,
    },

    // Refinance Goals
    refinanceGoal: {
      label: 'Refinance Goal',
      type: 'select',
      required: true,
      description: 'Primary goal of the refinance',
      options: [
        { value: 'lower_payment', label: 'Lower Monthly Payment' },
        { value: 'lower_rate', label: 'Lower Interest Rate' },
        { value: 'cash_out', label: 'Cash Out Equity' },
        { value: 'shorter_term', label: 'Shorter Loan Term' },
        { value: 'remove_pmi', label: 'Remove PMI' },
        { value: 'consolidate_debt', label: 'Consolidate Debt' },
      ],
    },
    targetMonthlySavings: {
      label: 'Target Monthly Savings',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Target monthly payment savings',
      placeholder: '200',
      min: 0,
      max: 10000,
    },
    targetRate: {
      label: 'Target Interest Rate',
      type: 'number',
      unit: 'percentage',
      required: false,
      description: 'Target interest rate for refinance',
      placeholder: '4.0',
      min: 0.1,
      max: 25,
    },
    cashOutAmount: {
      label: 'Cash Out Amount',
      type: 'number',
      unit: 'currency',
      required: false,
      description: 'Amount of cash to take out in refinance',
      placeholder: '0',
      min: 0,
      max: 1000000,
    },

    // Reporting Preferences
    currency: {
      label: 'Currency',
      type: 'select',
      required: true,
      description: 'Currency for calculations and display',
      options: [
        { value: 'USD', label: 'US Dollar ($)' },
        { value: 'EUR', label: 'Euro (€)' },
        { value: 'GBP', label: 'British Pound (£)' },
        { value: 'CAD', label: 'Canadian Dollar (C$)' },
        { value: 'AUD', label: 'Australian Dollar (A$)' },
      ],
    },
    displayFormat: {
      label: 'Display Format',
      type: 'select',
      required: true,
      description: 'Format for displaying numerical results',
      options: [
        { value: 'currency', label: 'Currency' },
        { value: 'percentage', label: 'Percentage' },
        { value: 'decimal', label: 'Decimal' },
      ],
    },
    includeCharts: {
      label: 'Include Charts',
      type: 'boolean',
      required: true,
      description: 'Include visual charts in the analysis',
    },
  },
  outputs: {
    // Core Metrics
    monthlyPaymentSavings: {
      label: 'Monthly Payment Savings',
      type: 'number',
      unit: 'currency',
      description: 'Monthly payment reduction from refinancing',
    },
    interestSavings: {
      label: 'Interest Savings',
      type: 'number',
      unit: 'currency',
      description: 'Total interest savings over the loan term',
    },
    breakEvenMonths: {
      label: 'Break-Even Months',
      type: 'number',
      unit: 'months',
      description: 'Number of months to break even on closing costs',
    },
    netSavings: {
      label: 'Net Savings',
      type: 'number',
      unit: 'currency',
      description: 'Net financial benefit of refinancing',
    },
    returnOnInvestment: {
      label: 'Return on Investment',
      type: 'number',
      unit: 'percentage',
      description: 'ROI of refinancing investment',
    },
    riskScore: {
      label: 'Risk Score',
      type: 'number',
      unit: 'score',
      description: 'Risk assessment score (0-100)',
    },

    // Payment Analysis
    newMonthlyPayment: {
      label: 'New Monthly Payment',
      type: 'number',
      unit: 'currency',
      description: 'Monthly payment for the new loan',
    },
    paymentSavingsPercentage: {
      label: 'Payment Savings %',
      type: 'number',
      unit: 'percentage',
      description: 'Percentage reduction in monthly payment',
    },

    // Cost Analysis
    totalRefinanceCost: {
      label: 'Total Refinance Cost',
      type: 'number',
      unit: 'currency',
      description: 'Total cost of refinancing',
    },
    breakEvenDate: {
      label: 'Break-Even Date',
      type: 'date',
      description: 'Date when refinancing costs are recovered',
    },
    breakEvenAmount: {
      label: 'Break-Even Amount',
      type: 'number',
      unit: 'currency',
      description: 'Total savings needed to break even',
    },

    // Interest Analysis
    interestSavingsPercentage: {
      label: 'Interest Savings %',
      type: 'number',
      unit: 'percentage',
      description: 'Percentage reduction in total interest',
    },
    totalInterestPaid: {
      label: 'Total Interest Paid',
      type: 'number',
      unit: 'currency',
      description: 'Total interest paid over loan term',
    },

    // Cash Flow Analysis
    monthlyCashFlow: {
      label: 'Monthly Cash Flow',
      type: 'number',
      unit: 'currency',
      description: 'Monthly cash flow improvement',
    },
    annualCashFlow: {
      label: 'Annual Cash Flow',
      type: 'number',
      unit: 'currency',
      description: 'Annual cash flow improvement',
    },
    totalCashFlow: {
      label: 'Total Cash Flow',
      type: 'number',
      unit: 'currency',
      description: 'Total cash flow improvement over analysis period',
    },

    // Equity Analysis
    currentEquity: {
      label: 'Current Equity',
      type: 'number',
      unit: 'currency',
      description: 'Current equity in the property',
    },
    newEquity: {
      label: 'New Equity',
      type: 'number',
      unit: 'currency',
      description: 'Equity after refinancing',
    },
    equityChange: {
      label: 'Equity Change',
      type: 'number',
      unit: 'currency',
      description: 'Change in equity from refinancing',
    },

    // Tax Analysis
    taxDeductionSavings: {
      label: 'Tax Deduction Savings',
      type: 'number',
      unit: 'currency',
      description: 'Tax savings from mortgage interest deduction',
    },
    afterTaxSavings: {
      label: 'After-Tax Savings',
      type: 'number',
      unit: 'currency',
      description: 'Savings after accounting for tax benefits',
    },
    effectiveRate: {
      label: 'Effective Rate',
      type: 'number',
      unit: 'percentage',
      description: 'Effective interest rate after tax benefits',
    },

    // Investment Analysis
    netPresentValue: {
      label: 'Net Present Value',
      type: 'number',
      unit: 'currency',
      description: 'NPV of refinancing decision',
    },
    internalRateOfReturn: {
      label: 'Internal Rate of Return',
      type: 'number',
      unit: 'percentage',
      description: 'IRR of refinancing investment',
    },
  },
  features: [
    'Comprehensive refinance analysis with break-even calculations',
    'Payment and interest savings analysis',
    'Cash flow and equity impact assessment',
    'Tax benefit calculations and effective rate analysis',
    'ROI and NPV calculations for investment decision making',
    'Risk assessment and scoring',
    'Multiple refinance type support (rate/term, cash-out, cash-in)',
    'Detailed cost breakdown and analysis',
    'Amortization comparison and timeline analysis',
    'Sensitivity and scenario analysis',
    'Visual charts and reporting options',
  ],
  examples: [
    {
      name: 'Rate and Term Refinance',
      description: 'Refinancing from 5.5% to 4.0% to lower monthly payments',
      inputs: {
        currentLoanAmount: 300000,
        currentInterestRate: 5.5,
        currentLoanTerm: 30,
        newLoanAmount: 280000,
        newInterestRate: 4.0,
        newLoanTerm: 30,
        refinanceType: 'rate_term',
        propertyValue: 350000,
        closingCosts: 5000,
        borrowerIncome: 80000,
        borrowerCreditScore: 750,
        borrowerDebtToIncomeRatio: 35,
        borrowerTaxRate: 25,
        analysisPeriod: 30,
        refinanceGoal: 'lower_payment',
      },
    },
    {
      name: 'Cash-Out Refinance',
      description: 'Taking cash out to pay off high-interest debt',
      inputs: {
        currentLoanAmount: 250000,
        currentInterestRate: 4.5,
        currentLoanTerm: 30,
        newLoanAmount: 300000,
        newInterestRate: 4.0,
        newLoanTerm: 30,
        refinanceType: 'cash_out',
        propertyValue: 400000,
        closingCosts: 6000,
        borrowerIncome: 90000,
        borrowerCreditScore: 720,
        borrowerDebtToIncomeRatio: 40,
        borrowerTaxRate: 28,
        analysisPeriod: 30,
        refinanceGoal: 'consolidate_debt',
        cashOutAmount: 50000,
      },
    },
    {
      name: 'Shorten Loan Term',
      description: 'Refinancing to a 15-year term to pay off faster',
      inputs: {
        currentLoanAmount: 200000,
        currentInterestRate: 4.5,
        currentLoanTerm: 30,
        newLoanAmount: 200000,
        newInterestRate: 3.5,
        newLoanTerm: 15,
        refinanceType: 'rate_term',
        propertyValue: 250000,
        closingCosts: 4000,
        borrowerIncome: 75000,
        borrowerCreditScore: 780,
        borrowerDebtToIncomeRatio: 30,
        borrowerTaxRate: 22,
        analysisPeriod: 15,
        refinanceGoal: 'shorter_term',
      },
    },
  ],
  relatedCalculators: [
    'mortgage-payment',
    'mortgage-qualification',
    'mortgage-points',
    'mortgage-rate-lock',
    'mortgage-vs-rent',
    'debt-to-income',
    'housing-expense-ratio',
    'loan-to-value',
  ],
};